[build]
  publish = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'self' https://ka-f.fontawesome.com; style-src 'self' 'unsafe-inline' https://ka-f.fontawesome.com; script-src 'self' 'unsafe-inline' https://kit.fontawesome.com; img-src 'self' data:; font-src 'self' https://ka-f.fontawesome.com;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
